import type { Metadata } from 'next'
import { Saira_Semi_Condensed } from 'next/font/google'
import './globals.css'

// React Query
import Providers from './providers'

// Atoms
import { Pokedex } from '@atoms'

const sairaSemiCondensed = Saira_Semi_Condensed({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-sairaSemiCondensed',
})

export const metadata: Metadata = {
  title: 'Pokedex App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={sairaSemiCondensed.className}>
        <Providers>
          <Pokedex>{children}</Pokedex>
        </Providers>
      </body>
    </html>
  )
}
