import type { Metadata } from 'next'
import { Inter, Saira_Semi_Condensed } from 'next/font/google'
import './globals.css'

const sairaSemiCondensed = Saira_Semi_Condensed({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-sairaSemiCondensed',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={sairaSemiCondensed.className}>{children}</body>
    </html>
  )
}
